### ISSUE TITLE
DOM: Document Object Model

### ISSUE THREAD

**Issue by lorecrafting** [alexakfk/wordle#2]
I'd familiarize yourself with the Document Object Model: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

It's basically the browsers API and different things you can do to interface with it.

This topic is worth using multiple resources to research and learn from.

**Comment by alexakfk** [comment]
Thank you! Will definitely get more familiar with the DOM, and some of the properties I might be able to use.

**Comment by lorecrafting** [comment]
💯
