### ISSUE TITLE
README: How to set up development environment

### ISSUE THREAD

**Issue by lorecrafting** [alexakfk/wordle#3]
There should be a README for the Github project that shows how I should set up my development environment and what prerequisites I need.

**Comment by alexakfk** [comment]
I created a quick README. Let me know if there is anything else I should include :)

**Comment by lorecrafting** [comment]
Cool! Looks good!

Are you familiar with Node, or Npm?  

It could be helpful to use something like `live-server` for your development environment and workflow.
https://www.npmjs.com/package/live-server

**Comment by alexakfk** [comment]
Had not heard about either Node or NPM, but it definitely looks useful. Thank you!
